version: '3'

services:
  mysql:
    image: mariadb
    ports:
    - 3306:3306

    environment:
      MARIADB_USER: brawltime
      MARIADB_PASSWORD: brawltime
      MARIADB_DATABASE: brawltime
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  clickhouse:
    image: clickhouse/clickhouse-server:25.4
    ports:
      - 8123:8123
      - 9000:9000

    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
