version: '3'

services:
  mysql:
    image: mariadb
    ports:
    - 3306:3306

    environment:
      MARIADB_USER: brawltime
      MARIADB_PASSWORD: brawltime
      MARIADB_DATABASE: brawltime
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  clickhouse:
    image: clickhouse/clickhouse-server:22.6
    ports:
    - 8123:8123
    - 9000:9000

    deploy:
      resources:
        limits:
          memory: 750M
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
