import { ManifestOptions } from "vite-plugin-pwa";
import { themeColor } from "../theme-colors.config.js";

export default {
  id: '/?standalone=true',
  start_url: '/?standalone=true',
  name: 'Brawl Time Ninja',
  short_name: 'Brawl Time',
  description: 'Track Brawl Stars stats, hours played and view Tier Lists.',
  theme_color: themeColor,
  icons: [
  // generated by generate-pwa-assets
  {
    "src": "/icons/pwa-64x64.png",
    "sizes": "64x64",
    "type": "image/png"
  },
  {
    "src": "/icons/pwa-192x192.png",
    "sizes": "192x192",
    "type": "image/png"
  },
  {
    "src": "/icons/pwa-512x512.png",
    "sizes": "512x512",
    "type": "image/png"
  },
  {
    "src": "/icons/maskable-icon-512x512.png",
    "sizes": "512x512",
    "type": "image/png",
    "purpose": "maskable"
  }],
} satisfies Partial<ManifestOptions>
