version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
    - 8123:8123

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  mysql:
    image: mariadb
    ports:
    - 3306:3306

    environment:
      MARIADB_USER: brawltime
      MARIADB_PASSWORD: brawltime
      MARIADB_DATABASE: brawltime
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
